vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix:         '%app.path.plant_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.plant_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true